// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'This platform is not configured for Firebase.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZSmyF9my39rqlS6RBQVak5obnRDr6O2E',
    appId: '1:901876119381:web:828fa3ec5fa301422f61dc',
    messagingSenderId: '901876119381',
    projectId: 'careloop-a975b',
    authDomain: 'careloop-a975b.firebaseapp.com',
    databaseURL: 'https://careloop-a975b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careloop-a975b.firebasestorage.app',
  );

  // 🌐 WEB CONFIG

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_D_zXPrDpM0mdke1spGYVChASk1oGW9g',
    appId: '1:901876119381:android:a9c5568493a4df2a2f61dc',
    messagingSenderId: '901876119381',
    projectId: 'careloop-a975b',
    databaseURL: 'https://careloop-a975b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careloop-a975b.firebasestorage.app',
  );

  // 📱 ANDROID CONFIG
}